### ISSUE TITLE
Update Quarkus Runtime to 1.4.2.Final

### ISSUE THREAD

**Issue by psrna** [redhat-developer/intellij-quarkus#71] opened 2020-04-07 13:36 UTC
Currently, the default Quarkus runtime is outdated (0.17) and also there is an error when trying to download the jar.

**Comment by zcervink** [comment] 2020-05-06 09:41
@psrna I have found a workaround you asked me for at our last meeting. Until the issue is not resolved, you can download and add the latest quarkus-core manually. Here is the link that worked for me:
- https://mvnrepository.com/artifact/io.quarkus/quarkus-core

**Comment by psrna** [comment] 2020-05-06 09:45
Yes, I know about the workaround, that's how I did it ;) But anyway, from the UX and developer adoption perspective, we should ship latest/greates quarkus runtime.

**Comment by zcervink** [comment] 2020-05-06 16:48
@psrna looks like a job for me. And here we go - updated and tested, download works with no errors. I am gonna me a pull request.
<img width="702" alt="Snímek obrazovky 2020-05-06 v 18 47 15" src="https://user-images.githubusercontent.com/43820055/81204851-224f2780-8fca-11ea-91b7-8591bc84e59f.png">

**Comment by zcervink** [comment] 2020-05-06 17:03
> Yes, I know about the workaround, that's how I did it ;) But anyway, from the UX and developer adoption perspective, we should ship latest/greates quarkus runtime.

ok, you are writing "latest/greates", I upgraded to 1.4.2.Final and I am also going to update the title of this issue.

**Comment by zcervink** [comment] 2020-05-06 17:06
@psrna Well, I have not the permissions to edit the title of your issue. Please update the title by yourself (update the version to 1.4.2.Final), or leave it as it is. It is up to you.

**Comment by zcervink** [comment] 2020-05-07 14:04
@psrna PR has been merged. Can you please grand me the permissions to close this issue? Or you can do that for me?
Of course we have to close the duplicate issue as well (https://github.com/redhat-developer/intellij-quarkus/issues/64)

**Comment by jeffmaury** [comment] 2020-05-07 15:02
@zcervink you don't need to close the issue if you use the Fixes# notation in your PR. But will see how to give you more priviledges

**Closed** 2020-05-07 15:02 UTC
