### ISSUE TITLE
OpenAPI properties not listed in application.properties file

### ISSUE THREAD

**Issue by rmarting** [redhat-developer/intellij-quarkus#241] opened 2020-09-23 12:28 UTC
My Application includes the following OpenAPI extension from the latest Quarkus 1.8.1.Final version:

```
<!-- Open API -->
<dependency>
   <groupId>io.quarkus</groupId>
   <artifactId>quarkus-smallrye-openapi</artifactId>
</dependency>
```

However when I tried to review the properties in the application.properties file, the **mp.openapi.** are not listed to be autocompleted.

Environment:

- IntelliJ IDEA 2020.2.2 (Ultimate Edition) Build Number: 202.7319.50
- JDK:
```
idea-IU-201.8743.12/jbr/bin 
❯ ./java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment JBR-11.0.8.10-944.31-jcef (build 11.0.8+10-b944.31)
OpenJDK 64-Bit Server VM JBR-11.0.8.10-944.31-jcef (build 11.0.8+10-b944.31, mixed mode)
```

- OS:
```
❯ uname -a
Linux redhat 5.8.9-200.fc32.x86_64 #1 SMP Mon Sep 14 18:28:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
idea-IU-201.8743.12/jbr/bin 
❯ cat /etc/redhat-release 
Fedora release 32 (Thirty Two)
```

Ideas?

**Comment by jeffmaury** [comment] 2020-09-28 08:53
I can't reproduce :

![image](https://user-images.githubusercontent.com/695993/94411342-c05dad00-0178-11eb-975c-06c42f0e4ef0.png)

But this on Windows and using Community 2019.2.
Will try to setup the same environment as yours

**Comment by jeffmaury** [comment] 2021-01-11 12:44
Closing as can't reproduce

**Closed by jeffmaury** 2021-01-11 12:44 UTC
