### ISSUE TITLE
Code assist in the application.properties file fails to open and fails to work

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#126] opened 2020-06-08 12:03 UTC
After a few minutes of working with application.properties file the context menu/completion fail to work, it just shows "No suggestions" for several cases such as "q", "qua", "quark" etc.

**Note:** this issue may appear as consequence as the following issue (if we resolve the following issue this issue may be also resolved):
- https://github.com/redhat-developer/intellij-quarkus/issues/124

<img width="467" alt="Snímek obrazovky 2020-06-08 v 13 18 38" src="https://user-images.githubusercontent.com/43820055/84026665-04d8f900-a98e-11ea-80e1-f6ce80e8be28.png">

**Comment by angelozerr** [comment] 2023-04-12 08:05
I think this issue is a problem with synchronisation between the editor content and the LSP language server. I did a fix with this problem at with https://github.com/redhat-developer/intellij-quarkus/pull/778  which will be embed in the release that we should create now.

I cannot reproduce the issue with this fix. I close this issue, @zcervink if you encounter the problem again (with the release which will come soon),please reopen it.

**Closed** 2023-04-12 08:05 UTC
Labels: bug
