### ISSUE TITLE
Report dialog should link to this issue tracker

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#738] opened 2023-02-02 14:06 UTC
When I click in the `Red-Hat` link I get redirected to https://www.redhat.com which doesn't help me trying to file issues. It should preferably have a link to this issue tracker 
![image](https://user-images.githubusercontent.com/54133/216346137-c211751a-9765-49f8-b46f-c2e017722b6e.png)

More info: https://plugins.jetbrains.com/docs/marketplace/plugin-overview-page.html#contacts-and-resources

**Comment by jeffmaury** [comment] 2023-02-02 15:14
This is not possible: the documentation you mention is about displaying info on the Marketplace but is not being processed by IntelliJ. The link provided by IntelliJ here is about the organization thus shared by several plugins.

See #591

**Comment by gastaldi** [comment] 2023-02-02 15:17
AFAIK changing the `url` attribute inside `vendor` should be enough?

**Comment by jeffmaury** [comment] 2023-02-02 15:54
> AFAIK changing the `url` attribute inside `vendor` should be enough?

Needs validation

**Comment by fbricon** [comment] 2023-06-26 21:19
Closing as duplicate of #517

**Closed by fbricon** 2023-06-26 21:19 UTC
Labels: duplicate
