### ISSUE TITLE
Application.properties autocomplete leaves mess at the end of the line

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#130] opened 2020-06-11 11:28 UTC
**Steps to reproduce:**
1) Create new project and open the application.properties file
2) Type "quark", the completion assist will show some suggestions
3) Press your left arrow key three times
4) Press enter, see the mess at the end of the line

<img width="351" alt="Snímek obrazovky 2020-06-11 v 13 27 08" src="https://user-images.githubusercontent.com/43820055/84380247-53cd9b00-abe7-11ea-9c45-621b3ab959b1.png">

**Comment by jeffmaury** [comment] 2020-06-15 09:24
Reproduced on Eclipse but not on VSCode that disables code assist as soon as back key is pressed. Need to talk with @angelozerr but fix in IJ may be tricky

**Comment by angelozerr** [comment] 2023-04-12 08:00
To be honnest with you, I don't know how to fix this issue. I need some investigation if we could manage something on LSP server side, but I fear it is a problem with LSP client.

**Comment by fbricon** [comment] 2023-06-09 13:06
I can't reproduce with 1.20. 
![Jun-09-2023 15-05-31](https://github.com/redhat-developer/intellij-quarkus/assets/148698/8905e476-f368-4d88-b788-9e57e8e14082)

Closing.

**Closed by fbricon** 2023-06-09 13:06 UTC
Labels: bug, lsp4ij, completion
