### ISSUE TITLE
Annoying recurring exception

### ISSUE THREAD

**Issue by mfortunat** [redhat-developer/intellij-quarkus#1322] opened 2024-04-17 00:20 UTC
Hi guys,

I know this issue:
============
**java.util.concurrent.CancellationException**
	at com.redhat.devtools.intellij.lsp4ij.internal.CancellationSupport.checkCanceled(CancellationSupport.java:76)
	at com.redhat.devtools.intellij.lsp4ij.AbstractLSPInlayProvider$1.collect(AbstractLSPInlayProvider.java:86)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:91)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$1(InlayHintsPass.kt:60)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:139)
	at com.intellij.openapi.application.impl.RwLockHolder.tryRunReadAction(RwLockHolder.kt:310)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:958)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:108)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:89)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

============

has been fixed a lot of time ago, so let me ask you: "When do you plan to release the fix?"

I tried, as you suggested, the nightly builds, but with them, I got even more exceptions from the Language Server plugin.

**Comment by fbricon** [comment] 2024-04-17 07:36
We should release some time in the next 3 weeks. 
Please please report any issues you see with the nightly builds (make sure you use the latest LSP4IJ build), because that's what we plan on releasing eventually. 
It'd be a shame to ship with problems we're not aware of because you did not report them.

**Comment by angelozerr** [comment] 2024-04-17 07:55
@mfortunat as said @fbricon please please use nightly builds of LSP4IJ and please report your all issues, thanks!

**Comment by mfortunat** [comment] 2024-04-19 08:14
@angelozerr, @fbricon 
OK guys, I installed both nightly builds.
Let's see how things are going in the following days.

**Comment by angelozerr** [comment] 2024-04-19 08:27
Thanks so much @mfortunat ! Hope you will not have annoying problems. Don't hesitate to report any issues.

**Comment by angelozerr** [comment] 2024-05-06 07:07
@mfortunat can we close this issue?

**Comment by mfortunat** [comment] 2024-05-06 12:07
Hi @angelozerr,
yes, I think it can be closed.
Thanks

**Comment by angelozerr** [comment] 2024-05-06 12:22
Thanks @mfortunat for your answer.

**Closed by angelozerr** 2024-05-06 12:22 UTC
Labels: bug

**Comment by ksdev-pl** [comment] 2024-08-16 20:51
Hello

Any idea when this fix goes on production? This exception appears constantly, again and again, making this plugin unusable.

**Comment by angelozerr** [comment] 2024-08-16 21:51
@ksdev-pl I am working on the release of IJ Quarkus and I hope thatvnext week I will able to do that.

Please install for the moment the nighty build. Hope you will change your feeling about IJ quarkus (I have seen your bad review on marketplace and I hope you will be more happy with the nighty build)

**Comment by angelozerr** [comment] 2024-08-17 13:22
@ksdev-pl I cannot reproduce this issue with nighty build, could you please add your starcktrace please.

**Comment by ksdev-pl** [comment] 2024-08-17 13:51
The issue with LSP? I don't know how to provoke it - it didn't reappear in few hours I was working on nightly build yesterday. If I'll see it again I'll post it on github.
Another issue I forgot to mention were duplicated inlay hints (like "2 references" above {#insert}). Together with CancellationException I saw them repeated 2-3 times ("2 references" above "2 references" above "2 references").
But this is also resolved by nightly build.

Thanks again.

**Comment by angelozerr** [comment] 2024-08-17 14:16
> The issue with LSP? I don't know how to provoke it - it didn't reappear in few hours I was working on nightly build yesterday. If I'll see it again I'll post it on github.
> Another issue I forgot to mention were duplicated inlay hints (like "2 references" above {#insert}). Together with CancellationException I saw them repeated 2-3 times ("2 references" above "2 references" above "2 references").
> But this is also resolved by nightly build.
> 
> Thanks again.

It means that with nighty build it is better? Please attach the error as soon as you will have it again

**Comment by ksdev-pl** [comment] 2024-08-17 14:27
> It means that with nighty build it is better?

On non-nightly (normal) version I saw:
- constant CancellationExceptions
- duplication of inlay hints 

After I moved to nightly build:
- I saw LSP exception (I'm 90% sure that it's "LSP", as it's from memory), which I don't know how to repeat (but if it will I'll post it on github)
- no more CancellationExceptions
- no more duplication of inlay hints

So for few hours I was working with nightly build I worked without any issues, definitely better with nightly build.

**Comment by angelozerr** [comment] 2024-08-17 14:51
> > It means that with nighty build it is better?
> 
> On non-nightly (normal) version I saw:
> - constant CancellationExceptions
> - duplication of inlay hints 
> 
> After I moved to nightly build:
> - I saw LSP exception (I'm 90% sure that it's "LSP", as it's from memory), which I don't know how to repeat (but if it will I'll post it on github)
> - no more CancellationExceptions
> - no more duplication of inlay hints
> 
> So for few hours I was working with nightly build I worked without any issues, definitely better with nightly build.

Thanks for your feedback! I am waiting for your issue to try to fix it when you will have it.

Please adjust your review if you think it is better with nighthy build. I hope I will able to create the release next week.

**Comment by ksdev-pl** [comment] 2024-08-17 14:53
I removed the review. Don't be discouraged and good luck.

**Comment by angelozerr** [comment] 2024-08-19 05:42
Thanks @ksdev-pl ! And dont hesitate to create anyv issues.

**Comment by angelozerr** [comment] 2024-08-26 13:27
@ksdev-pl @mfortunat we are pleased to announce that you can now install Quarkus Tools 2.0.0 https://plugins.jetbrains.com/plugin/13234-quarkus-tools/edit/versions !

**Comment by mfortunat** [comment] 2024-08-26 14:37
Thanks, @angelozerr, that's great news!
