### ISSUE TITLE
Non recognized symbols in the ExampleResource.java file

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#143] opened 2020-06-20 10:48 UTC
I have investigated and I have found, that this issue appear in 2 situations:

1) this is probably not an issue, but I have decided to mention it anyway - when you open the ExampleResource.java before the indexing finishes, you will see this issue
2) sometimes the issue remains after the indexing is done, this situation is connected to the following issue (maybe we should open the issue) - https://github.com/redhat-developer/intellij-quarkus/issues/133

**See the issue and see the bottom line with warning message:**
<img width="1109" alt="Snímek obrazovky 2020-06-19 v 17" src="https://user-images.githubusercontent.com/43820055/85199987-11494400-b2f4-11ea-9be9-38caf8fde494.png">

**Comment by fbricon** [comment] 2023-06-26 17:55
Can't reproduce with latest plugin. Closing

**Closed by fbricon** 2023-06-26 17:55 UTC
Labels: bug
