### ISSUE TITLE
Error while editing a properties YAML file. It happens any time I add a new element.

### ISSUE THREAD

**Issue by mfortunat** [redhat-developer/intellij-quarkus#1316] opened 2024-03-11 07:46 UTC
IJ version: 2023.3.4
Build #IU-233.14475.28, built on February 13, 2024

NOTE in this case I was adding the "auto" element under an "mp.messaging.incoming.{name}" for configuring the "auto.offset.reset".

Failed to notify classpath resource change

java.lang.RuntimeException: Cannot invoke (class=MicroProfileProjectListener, method=sourceFilesChanged, topic=com.redhat.devtools.intellij.lsp4mp4ij.classpath.ClasspathResourceChangedManager)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy15/jdk.proxy15.$Proxy334.sourceFilesChanged(Unknown Source)
	at com.redhat.devtools.intellij.lsp4mp4ij.classpath.ClasspathResourceChangedNotifier.notifyChanges(ClasspathResourceChangedNotifier.java:110)
	at com.redhat.devtools.intellij.lsp4mp4ij.classpath.ClasspathResourceChangedNotifier$1.run(ClasspathResourceChangedNotifier.java:88)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: while scanning a simple key
 in 'reader', line 58, column 9:
            au
            ^
could not find expected ':'
 in 'reader', line 61, column 1:
    
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:502)
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:307)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:237)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:637)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:434)
	at com.redhat.devtools.intellij.quarkus.psi.internal.utils.YamlUtils.loadYamlAsProperties(YamlUtils.java:42)
	at com.redhat.devtools.intellij.quarkus.psi.internal.providers.YamlConfigSource.loadConfig(YamlConfigSource.java:43)
	at com.redhat.devtools.intellij.quarkus.psi.internal.providers.YamlConfigSource.loadConfig(YamlConfigSource.java:34)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.project.AbstractConfigSource.reload(AbstractConfigSource.java:195)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.project.PsiMicroProfileProject.lambda$evictConfigSourcesCache$2(PsiMicroProfileProject.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.project.PsiMicroProfileProject.evictConfigSourcesCache(PsiMicroProfileProject.java:197)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.project.PsiMicroProfileProjectManager$MicroProfileProjectListener.sourceFilesChanged(PsiMicroProfileProjectManager.java:65)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
	... 9 more

**Comment by fbricon** [comment] 2024-03-11 09:31
Duplicate of #1282.

Until the next release, you can install a [nightly build of intellij-quarkus](https://github.com/redhat-developer/intellij-quarkus?tab=readme-ov-file#testing-nightly-builds)  (which requires a [nightly build of LSP4IJ](https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds))

**Closed by fbricon** 2024-03-11 09:31 UTC
