### ISSUE TITLE
Cannot resolve configuration item 'level' (on quarkus.log.category)

### ISSUE THREAD

**Issue by dxps** [redhat-developer/intellij-quarkus#732] opened 2023-01-20 14:52 UTC
Hi everyone!

According to Quarkus Logging guide, [Runtime configuration](https://quarkus.io/guides/logging#runtime-configuration) section, a syntax such as `quarkus.log.category."whatever.package.name".level=DEBUG` works.

And yes, it works. Both without (as in the syntax above) or with profile (as shown in the screenshot below).

![image](https://user-images.githubusercontent.com/14140226/213728528-b45b6241-6615-4d41-b65d-7e9b15fdf631.png)

However, the editor complains about it.

Context:
- IntelliJ IDEA 2022.3.1 (Ultimate Edition)
- Quarkus Tools 1.15.0.308
- Pop!_OS 22.04 LTS

Thank you!

**Comment by adietish** [comment] 2023-04-05 13:27
@jeffmaury this feature is missing, yet, correct?

**Comment by jeffmaury** [comment] 2023-04-05 16:15
Should not because it is based on the LSP

**Comment by fbricon** [comment] 2023-06-26 21:25
@dxps works for me:
<img width="448" alt="Screenshot 2023-06-26 at 23 23 50" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/d2d2b652-79d1-4cf6-ae29-f2a7d9fa1354">


can you check with the latest plugin version?

**Comment by angelozerr** [comment] 2023-06-26 21:29
@fbricon we never manage this error message  and when property name has an error we highlight  the full property name and not just a given part like level in this issue 

This error comes from an another plugin or perhaps from quarkus support from Jetbrains?

**Comment by fbricon** [comment] 2023-06-27 06:21
Ok so it must have come from the built-in Quarks support from Ultimate. I tried with ultimate EAP and couldn't reproduce.
Closing.

**Closed by fbricon** 2023-06-27 06:21 UTC
Labels: bug, quarkus, validation

**Comment by dxps** [comment] 2023-06-27 13:17
I can confirm it's all good now. Thanks a lot for the fix! :pray: 
![image](https://github.com/redhat-developer/intellij-quarkus/assets/14140226/87409ca0-e58a-4808-af83-4b3206a09a74)
