### ISSUE TITLE
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'qualifiedName' of com/intellij/psi/impl/JavaPsiFacadeImpl.findClass must not be null

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#852] opened 2023-05-10 23:18 UTC
This happened while the IDE was indexing my local clone of https://github.com/quarkusio/quarkus

Using 1.18.0.373: 

```java
Cannot compute MicroProfile properties for the Java element 'PsiClass:NativeConfig'.

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'qualifiedName' of com/intellij/psi/impl/JavaPsiFacadeImpl.findClass must not be null
	at com.intellij.psi.impl.JavaPsiFacadeImpl.$$$reportNull$$$0(JavaPsiFacadeImpl.java)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.utils.PsiTypeUtils.findType(PsiTypeUtils.java:147)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:158)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:216)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.processConfigMapping(QuarkusConfigMappingProvider.java:120)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.processAnnotation(QuarkusConfigMappingProvider.java:90)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.AbstractAnnotationTypeReferencePropertiesProvider.processAnnotation(AbstractAnnotationTypeReferencePropertiesProvider.java:58)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.AbstractAnnotationTypeReferencePropertiesProvider.collectProperties(AbstractAnnotationTypeReferencePropertiesProvider.java:48)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.collectProperties(PropertiesManager.java:126)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.lambda$getMicroProfileProjectInfo$1(PropertiesManager.java:103)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.lambda$getMicroProfileProjectInfo$2(PropertiesManager.java:103)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:143)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:100)
	at com.redhat.devtools.intellij.quarkus.QuarkusProjectService.lambda$computeSchema$9(QuarkusProjectService.java:225)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:958)
	at com.redhat.devtools.intellij.quarkus.QuarkusProjectService.lambda$computeSchema$10(QuarkusProjectService.java:223)
	at com.intellij.openapi.project.SmartModeScheduler.doRun(SmartModeScheduler.kt:124)
	at com.intellij.openapi.project.SmartModeScheduler.runAllWhileSmart(SmartModeScheduler.kt:117)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by angelozerr** [comment] 2023-06-06 14:30
Duplicate of https://github.com/redhat-developer/intellij-quarkus/issues/913 which has been fixed

**Closed by angelozerr** 2023-06-06 14:30 UTC
Labels: bug
