### ISSUE TITLE
AlreadyDisposedException appears after new Quarkus project has been created

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#161] opened 2020-06-29 20:30 UTC
This Exception has appeared only once. I tried to reproduce it again, but I was unsuccessful. I have no steps to reproduce, but I know this exception has appeared after I have repeatedly created and deleted new Quarkus project (+ opening and closing the IDE).

```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create Project (name=code-with-quarkus, containerState=DISPOSE_COMPLETED, componentStore=/Users/zcervink/Desktop/Bez názvu/code-with-quarkus/code-with-quarkus/code-with-quarkus/code-with-quarkus/code-with-quarkus.ipr)  because container is already disposed (container=Project (name=code-with-quarkus, containerState=DISPOSE_COMPLETED, componentStore=/Users/zcervink/Desktop/Bez názvu/code-with-quarkus/code-with-quarkus/code-with-quarkus/code-with-quarkus/code-with-quarkus.ipr) )
	at com.intellij.serviceContainer.ComponentManagerImpl.checkThatNotDisposedCompletely(ComponentManagerImpl.kt:439)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:415)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:394)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:24)
	at com.intellij.openapi.roots.impl.libraries.LibraryTablesRegistrarImpl.getLibraryTable(LibraryTablesRegistrarImpl.java:42)
	at com.intellij.openapi.roots.impl.libraries.LibraryTablesRegistrarImpl.getLibraryTableByLevel(LibraryTablesRegistrarImpl.java:47)
	at com.intellij.openapi.roots.impl.LibraryOrderEntryImpl.dispose(LibraryOrderEntryImpl.java:235)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:184)
	at com.intellij.openapi.util.ObjectTree.executeUnregistered(ObjectTree.java:197)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:128)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:116)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:106)
	at com.intellij.openapi.CompositeDisposable.dispose(CompositeDisposable.java:67)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:184)
	at com.intellij.openapi.util.ObjectTree.executeUnregistered(ObjectTree.java:197)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:128)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:116)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:106)
	at com.intellij.openapi.roots.impl.RootModelImpl.dispose(RootModelImpl.java:663)
	at com.intellij.openapi.roots.impl.ModuleRootManagerImpl$1.dispose(ModuleRootManagerImpl.java:103)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:149)
	at com.redhat.devtools.intellij.quarkus.QuarkusModuleUtil.ensureQuarkusLibrary(QuarkusModuleUtil.java:73)
	at com.redhat.devtools.intellij.quarkus.maven.QuarkusMavenProjectsProcessTask.perform(QuarkusMavenProjectsProcessTask.java:42)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor.doProcessPendingTasks(MavenProjectsProcessor.java:141)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor.access$000(MavenProjectsProcessor.java:35)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor$1.run(MavenProjectsProcessor.java:110)
	at org.jetbrains.idea.maven.utils.MavenUtil.lambda$runInBackground$5(MavenUtil.java:488)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by fbricon** [comment] 2023-06-30 14:44
QuarkusMavenProjectsProcessTask no longer exists, the code calling QuarkusModuleUtil.ensureQuarkusLibrary has been refactored entirely, I can't reproduce this issue with the current codebase. 
Closing.

**Closed by fbricon** 2023-06-30 14:44 UTC
Labels: bug, quarkus, wizard
