### ISSUE TITLE
Creating new Quarkus project over and over causes default project location to be longer and longer

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#381] opened 2021-03-22 17:34 UTC
Default project location in the wizard repeats "code-with-quarkus" over and over and creates nested folders.

<img width="1295" alt="Snímek obrazovky 2021-03-22 v 17 15 25" src="https://user-images.githubusercontent.com/43820055/112022066-35131200-8b32-11eb-88d9-e7b7cf059c0d.png">

**Comment by fbricon** [comment] 2023-06-26 11:54
Can't reproduce with latest version of the plugin. Closing.

**Closed by fbricon** 2023-06-26 11:54 UTC
Labels: bug, quarkus, wizard
