### ISSUE TITLE
Cannot Create Class alert in Intellij Ultimate

### ISSUE THREAD

**Issue by yazalulloa** [redhat-developer/intellij-quarkus#1225] opened 2023-10-15 23:27 UTC
Everytime I try to create a new Java class it pops that alert, it creates the file, but the package and the class definition is missing.

Ubuntu 22.04.3
IntelliJ IDEA 2023.2.3 (Ultimate Edition)
Build #IU-232.10072.27, built on October 11, 2023
Quarkus Tools: com.redhat.devtools.intellij.quarkus (1.28.0.553)

![image](https://github.com/redhat-developer/intellij-quarkus/assets/33322056/344bf7ef-d714-48e7-9a23-b5c4ed1bb3eb)

**Comment by angelozerr** [comment] 2023-10-16 08:44
Ij Quarkus 1.28.0.553 doesn't work with IDEA 2023.2.3 because IJ change a lot of behavior of some API.

I create several PRs to fix that. We plan to release ASAP, but I suggest that you try to install zip from https://github.com/redhat-developer/intellij-quarkus/actions/runs/6509661972 by following instructions at https://github.com/redhat-developer/intellij-quarkus#testing-the-ci-builds

If you could do that and give us feedback, it should be very welcome. Thanks!

**Comment by fbricon** [comment] 2023-10-30 16:44
Do you still have this issue with v1.29.0 or the latest [nightly build](https://github.com/redhat-developer/intellij-quarkus/issues/1225)?

Could you attach [your idea.log(s)](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)

**Comment by fbricon** [comment] 2023-11-02 17:24
Closing as I can't reproduce with the latest release and OP hasn't responded.

**Closed by fbricon** 2023-11-02 17:24 UTC
Labels: bug, qute, lsp4ij, quarkus

**Comment by yazalulloa** [comment] 2023-11-02 19:15
Sorry didn't see the notifications

**Comment by yazalulloa** [comment] 2023-11-02 19:21
It works with 1.29, thanks
