### ISSUE TITLE
Code completion not working with application.yml

### ISSUE THREAD

**Issue by micheljung** [redhat-developer/intellij-quarkus#358] opened 2021-02-07 16:28 UTC
#50 added support for application.yml

However:

![image](https://user-images.githubusercontent.com/1864183/107152699-965b9900-6969-11eb-9186-c34e05da3f75.png)
![image](https://user-images.githubusercontent.com/1864183/107152706-9fe50100-6969-11eb-834c-0bfb9d6707a2.png)

Version 1.3.0.103:
![image](https://user-images.githubusercontent.com/1864183/107152722-b68b5800-6969-11eb-8155-013f096f5f09.png)

Using`io.quarkus:quarkus-config-yaml`:

![image](https://user-images.githubusercontent.com/1864183/107152726-c3a84700-6969-11eb-8285-db86fe9c380a.png)

**Comment by jeffmaury** [comment] 2021-02-07 18:36
Duplicate of #329

**Closed by jeffmaury** 2021-02-07 18:36 UTC
