### ISSUE TITLE
Qute Support breaks in Ultimate

### ISSUE THREAD

**Issue by Keyruu** [redhat-developer/intellij-quarkus#1126] opened 2023-08-24 06:55 UTC
I'm currently really struggling with getting proper Qute Support into the IntelliJ Ultimate Edition. If I install the bundled Quarkus Extension of IntelliJ and the Quarkus Tools, it doesn't give me any auto-completion. If I disable the bundled extension and re-enable it in the running IDE, it works as intended. But after the next restart it just goes back to no support at all.
This probably has something to do with IntelliJ hijacking the Qute file type at the start of the IDE, does anybody know a way around this?
For me to fix this I took these steps: Remove all mappings in the Qute File Type of the Quarkus Tools exentsion and after applying that, to re add "*.qute.html". Then it seems to just work as intendend.

**Comment by fbricon** [comment] 2023-08-24 09:17
If you manually override the file type to "our" Qute type, this will survive restarts:

<img width="1396" alt="Screenshot 2023-08-24 at 11 12 39" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/9327460d-cc04-4dce-b93c-f861ddf6db71">
<img width="377" alt="Screenshot 2023-08-24 at 11 13 00" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/3c9e9965-628c-42ce-b625-dfbaa68c25c3">
<img width="1397" alt="Screenshot 2023-08-24 at 11 13 46" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/02512645-5bb1-4996-bc8a-f223588e4121">

**Comment by fbricon** [comment] 2023-08-24 09:24
I'm closing this issue as a duplicate of #979

**Closed** 2023-08-24 09:25 UTC
Labels: duplicate
